# https://taskfile.dev

version: '3'

tasks:

  default:
    cmds:
      - task -l
    silent: true

  init:
    desc: Initialises the project
    sources:
      - mise.toml
    generates:
      - mise.lock
    cmds:
      - mise install

  test:
    desc: Test the project
    cmds:
      - TMPDIR=$(mktemp -d) && boilerplate --template-url . --output-folder $TMPDIR && rm -r $TMPDIR
